### ISSUE TITLE
Postgres backup CronJob experiences OOMKilled

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/ansible-infrastructure#5]
It's probably worth removing or considerably increasing the CronJob's memory limit. Current settings are: -

```
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
